Repository Cyfrin/aderyn, pull requests merged in 2025-03, with the labels that each got.

#817 docs: Update URLs in README.md
  README.md
Labels: external-contribution

#826 Remove remappings from aderyn toml
  aderyn_driver/src/config_helpers.rs
Labels: priority-high

#825 feat: Make `src` single folder instead of vector of paths
  aderyn/src/main.rs
  aderyn_driver/src/config_helpers.rs
  aderyn_driver/src/driver.rs
  aderyn_driver/src/foundry_compiler_helpers.rs
  aderyn_driver/src/lib.rs
  aderyn_driver/src/process_auto.rs
  aderyn_driver/src/project_compiler_tests.rs
Labels: priority-high

#865 Update README.md
  README.md
Labels: priority-medium

#720 imp: Added `deny.toml` for managing licenses and rust crate security from advisories
  .github/workflows/cargo.yml
  deny.toml
Labels: priority-low
